# Copyright (C) 1991-2003 Altera Corporation
# Any  megafunction  design,  and related netlist (encrypted  or  decrypted),
# support information,  device programming or simulation file,  and any other
# associated  documentation or information  provided by  Altera  or a partner
# under  Altera's   Megafunction   Partnership   Program  may  be  used  only
# to program  PLD  devices (but not masked  PLD  devices) from  Altera.   Any
# other  use  of such  megafunction  design,  netlist,  support  information,
# device programming or simulation file,  or any other  related documentation
# or information  is prohibited  for  any  other purpose,  including, but not
# limited to  modification,  reverse engineering,  de-compiling, or use  with
# any other  silicon devices,  unless such use is  explicitly  licensed under
# a separate agreement with  Altera  or a megafunction partner.  Title to the
# intellectual property,  including patents,  copyrights,  trademarks,  trade
# secrets,  or maskworks,  embodied in any such megafunction design, netlist,
# support  information,  device programming or simulation file,  or any other
# related documentation or information provided by  Altera  or a megafunction
# partner, remains with Altera, the megafunction partner, or their respective
# licensors. No other licenses, including any licenses needed under any third
# party's intellectual property, are provided herein.

# Quartus II: Generate Tcl File for Project
# File: dom.tcl
# Generated on: Thu Feb 26 10:03:20 2004

# Load Quartus II Tcl Project package
package require ::quartus::project

set need_to_close_project 0
set make_assignments 1

# Check that the right project is open
if {[is_project_open]} {
	if {[string compare $quartus(project) "dom"]} {
		puts "Project dom is not open"
		set make_assignments 0
	}
} else {
	# Only open if not already open
	if {[project_exists dom]} {
		project_open -cmp dom dom
	} else {
		project_new dom
	}
	set need_to_close_project 1
}

# Make assignments
if {$make_assignments} {
	# Project Assignments
	set_global_assignment -name "COMPILER_SETTINGS" "dom"
	set_global_assignment -name "SIMULATOR_SETTINGS" "dom"
	set_global_assignment -name "SOFTWARE_SETTINGS" "Debug"
	set_global_assignment -name "SOFTWARE_SETTINGS" "Release"
	set_global_assignment -name "VHDL_FILE" "systimer.vhd"
	set_global_assignment -name "VHDL_FILE" "ahb_slave.vhd"
	set_global_assignment -name "VHDL_FILE" "ROC.vhd"
	set_global_assignment -name "VHDL_FILE" "constants.vhd"
	set_global_assignment -name "VHDL_FILE" "icecube_data_types.vhd"
	set_global_assignment -name "VHDL_FILE" "ctrl_data_types.vhd"
	set_global_assignment -name "VHDL_FILE" "FADC_input.vhd"
	set_global_assignment -name "VHDL_FILE" "ahb_master.vhd"
	set_global_assignment -name "VHDL_FILE" "ATWD_control.vhd"
	set_global_assignment -name "VHDL_FILE" "gray2bin.vhd"
	set_global_assignment -name "VHDL_FILE" "trigger.vhd"
	set_global_assignment -name "VHDL_FILE" "daq.vhd"
	set_global_assignment -name "VHDL_FILE" "ATWD_interface.vhd"
	set_global_assignment -name "VHDL_FILE" "mem_interface.vhd"
	set_global_assignment -name "VHDL_FILE" "FADC_interface.vhd"
	set_global_assignment -name "VHDL_FILE" "data_buffer.vhd"
	set_global_assignment -name "VHDL_FILE" "ADC_input.vhd"
	set_global_assignment -name "VHDL_FILE" "ADC_control.vhd"
	set_global_assignment -name "VHDL_FILE" "pingpong.vhd"
	set_global_assignment -name "VHDL_FILE" "pedestal_sub.vhd"
	set_global_assignment -name "VHDL_FILE" "domapp.vhd"
	set_global_assignment -name "VHDL_FILE" "compression.vhd"
	set_global_assignment -name "VHDL_FILE" "functions.vhd"
	set_global_assignment -name "VHDL_FILE" "slaveregister.vhd"

	set_global_assignment -name "ACLK_CAT" "OFF"
	set_global_assignment -name "ACLK_RULE_IMSZER_ADOMAIN" "OFF"
	set_global_assignment -name "ACLK_RULE_NO_SZER_ACLK_DOMAIN" "OFF"
	set_global_assignment -name "ACLK_RULE_SZER_BTW_ACLK_DOMAIN" "OFF"
	set_global_assignment -name "ASSG_CAT" "OFF"
	set_global_assignment -name "ASSG_RULE_MISSING_FMAX" "OFF"
	set_global_assignment -name "ASSG_RULE_MISSING_TIMING" "OFF"
	set_global_assignment -name "CLK_CAT" "OFF"
	set_global_assignment -name "CLK_RULE_ALL" "OFF"
	set_global_assignment -name "CLK_RULE_CLKNET_CLKSPINES" "OFF"
	set_global_assignment -name "CLK_RULE_COMB_CLOCK" "OFF"
	set_global_assignment -name "CLK_RULE_GATING_SCHEME" "OFF"
	set_global_assignment -name "CLK_RULE_INPINS_CLKNET" "OFF"
	set_global_assignment -name "CLK_RULE_INV_CLOCK" "OFF"
	set_global_assignment -name "CLK_RULE_MIX_EDGES" "OFF"
	set_global_assignment -name "HCPY_ALOAD_SIGNALS" "OFF"
	set_global_assignment -name "NONSYNCHSTRUCT_RULE_ASYN_RAM" "OFF"
	set_global_assignment -name "HCPY_CAT" "OFF"
	set_global_assignment -name "HCPY_EXCEED_RAM_USAGE" "OFF"
	set_global_assignment -name "HCPY_EXCEED_USER_IO_USAGE" "OFF"
	set_global_assignment -name "HCPY_ILLEGAL_HC_DEV_PKG" "OFF"
	set_global_assignment -name "HCPY_VREF_PINS" "OFF"
	set_global_assignment -name "NONSYNCHSTRUCT_CAT" "OFF"
	set_global_assignment -name "NONSYNCHSTRUCT_RULE_COMBLOOP" "OFF"
	set_global_assignment -name "NONSYNCHSTRUCT_RULE_COMB_DRIVES_RAM_WE" "OFF"
	set_global_assignment -name "NONSYNCHSTRUCT_RULE_DELAY_CHAIN" "OFF"
	set_global_assignment -name "NONSYNCHSTRUCT_RULE_DLATCH" "OFF"
	set_global_assignment -name "NONSYNCHSTRUCT_RULE_ILLEGAL_PULSE_GEN" "OFF"
	set_global_assignment -name "NONSYNCHSTRUCT_RULE_LATCH_UNIDENTIFIED" "OFF"
	set_global_assignment -name "NONSYNCHSTRUCT_RULE_MULTI_VIBRATOR" "OFF"
	set_global_assignment -name "NONSYNCHSTRUCT_RULE_REG_LOOP" "OFF"
	set_global_assignment -name "NONSYNCHSTRUCT_RULE_RIPPLE_CLK" "OFF"
	set_global_assignment -name "NONSYNCHSTRUCT_RULE_SRLATCH" "OFF"
	set_global_assignment -name "RESET_CAT" "OFF"
	set_global_assignment -name "RESET_RULE_ALL" "OFF"
	set_global_assignment -name "RESET_RULE_COMB_ASYNCH_RESET" "OFF"
	set_global_assignment -name "RESET_RULE_IMSYNCH_ASYNCH_DOMAIN" "OFF"
	set_global_assignment -name "RESET_RULE_IMSYNCH_EXRESET" "OFF"
	set_global_assignment -name "RESET_RULE_INPINS_RESETNET" "OFF"
	set_global_assignment -name "RESET_RULE_REG_ASNYCH" "OFF"
	set_global_assignment -name "RESET_RULE_UNSYNCH_ASYNCH_DOMAIN" "OFF"
	set_global_assignment -name "RESET_RULE_UNSYNCH_EXRESET" "OFF"
	set_global_assignment -name "SIGNALRACE_CAT" "OFF"
	set_global_assignment -name "SIGNALRACE_RULE_ASYNCHPIN_SYNCH_CLKPIN" "OFF"
	set_global_assignment -name "SIGNALRACE_RULE_TRISTATE" "OFF"
	set_global_assignment -name "TIMING_CAT" "OFF"
	set_global_assignment -name "TIMING_RULE_COIN_CLKEDGE" "OFF"
	set_global_assignment -name "TIMING_RULE_HIGH_FANOUTS" "OFF"
	set_global_assignment -name "TIMING_RULE_SHIFT_REG" "OFF"
	set_global_assignment -name "LIMIT_AHDL_INTEGERS_TO_32_BITS" "OFF"
	set_global_assignment -name "USE_LPM_FOR_AHDL_OPERATORS" "ON"
	set_global_assignment -name "ALLOW_POWER_UP_DONT_CARE" "ON"
	set_global_assignment -name "AUTO_CARRY_CHAINS" "ON"
	set_global_assignment -name "AUTO_CASCADE_CHAINS" "ON"
	set_global_assignment -name "AUTO_DELAY_CHAINS" "ON"
	set_global_assignment -name "AUTO_DSP_RECOGNITION" "ON"
	set_global_assignment -name "AUTO_GLOBAL_CLOCK" "ON"
	set_global_assignment -name "AUTO_GLOBAL_MEMORY_CONTROLS" "OFF"
	set_global_assignment -name "AUTO_GLOBAL_OE" "ON"
	set_global_assignment -name "AUTO_GLOBAL_REGISTER_CONTROLS" "ON"
	set_global_assignment -name "AUTO_FAST_INPUT_REGISTERS" "OFF"
	set_global_assignment -name "AUTO_LCELL_INSERTION" "ON"
	set_global_assignment -name "AUTO_MERGE_PLLS" "ON"
	set_global_assignment -name "AUTO_OPEN_DRAIN_PINS" "ON"
	set_global_assignment -name "AUTO_FAST_OUTPUT_ENABLE_REGISTERS" "OFF"
	set_global_assignment -name "AUTO_FAST_OUTPUT_REGISTERS" "OFF"
	set_global_assignment -name "AUTO_PARALLEL_EXPANDERS" "ON"
	set_global_assignment -name "AUTO_RAM_RECOGNITION" "ON"
	set_global_assignment -name "AUTO_IMPLEMENT_IN_ROM" "OFF"
	set_global_assignment -name "AUTO_SHIFT_REGISTER_RECOGNITION" "ON"
	set_global_assignment -name "AUTO_TURBO_BIT" "ON"
	set_global_assignment -name "CARRY_CHAIN_LENGTH" "48"
	set_global_assignment -name "MERCURY_CARRY_CHAIN_LENGTH" "48"
	set_global_assignment -name "FLEX10K_CARRY_CHAIN_LENGTH" "32"
	set_global_assignment -name "FLEX6K_CARRY_CHAIN_LENGTH" "32"
	set_global_assignment -name "STRATIX_CARRY_CHAIN_LENGTH" "70"
	set_global_assignment -name "CARRY_OUT_PINS_LCELL_INSERT" "ON"
	set_global_assignment -name "CASCADE_CHAIN_LENGTH" "2"
	set_global_assignment -name "DSP_BLOCK_BALANCING" "AUTO"
	set_global_assignment -name "REMOVE_DUPLICATE_LOGIC" "ON"
	set_global_assignment -name "REMOVE_DUPLICATE_REGISTERS" "ON"
	set_global_assignment -name "ENABLE_BUS_HOLD_CIRCUITRY" "OFF"
	set_global_assignment -name "IGNORE_CARRY_BUFFERS" "OFF"
	set_global_assignment -name "IGNORE_CASCADE_BUFFERS" "OFF"
	set_global_assignment -name "IGNORE_GLOBAL_BUFFERS" "OFF"
	set_global_assignment -name "IGNORE_LCELL_BUFFERS" "OFF"
	set_global_assignment -name "MAX7000_IGNORE_LCELL_BUFFERS" "AUTO"
	set_global_assignment -name "IGNORE_ROW_GLOBAL_BUFFERS" "OFF"
	set_global_assignment -name "IGNORE_SOFT_BUFFERS" "ON"
	set_global_assignment -name "MAX7000_IGNORE_SOFT_BUFFERS" "OFF"
	set_global_assignment -name "NORMAL_LCELL_INSERT" "ON"
	set_global_assignment -name "NOT_GATE_PUSH_BACK" "ON"
	set_global_assignment -name "APEX20K_OPTIMIZATION_TECHNIQUE" "SPEED"
	set_global_assignment -name "CYCLONE_OPTIMIZATION_TECHNIQUE" "AREA"
	set_global_assignment -name "MERCURY_OPTIMIZATION_TECHNIQUE" "AREA"
	set_global_assignment -name "FLEX10K_OPTIMIZATION_TECHNIQUE" "AREA"
	set_global_assignment -name "FLEX6K_OPTIMIZATION_TECHNIQUE" "AREA"
	set_global_assignment -name "MAX7000_OPTIMIZATION_TECHNIQUE" "SPEED"
	set_global_assignment -name "STRATIX_OPTIMIZATION_TECHNIQUE" "SPEED"
	set_global_assignment -name "PCI_IO" "OFF"
	set_global_assignment -name "PARALLEL_EXPANDER_CHAIN_LENGTH" "16"
	set_global_assignment -name "MAX7000_PARALLEL_EXPANDER_CHAIN_LENGTH" "4"
	set_global_assignment -name "AUTO_PACKED_REGISTERS" "OFF"
	set_global_assignment -name "AUTO_PACKED_REG_CYCLONE" "NORMAL"
	set_global_assignment -name "AUTO_PACKED_REGISTERS_STRATIX" "NORMAL"
	set_global_assignment -name "REMOVE_REDUNDANT_LOGIC_CELLS" "OFF"
	set_global_assignment -name "SLOW_SLEW_RATE" "OFF"
	set_global_assignment -name "STATE_MACHINE_PROCESSING" "AUTO"
	set_global_assignment -name "APEX20K_TECHNOLOGY_MAPPER" "LUT"
	set_global_assignment -name "MERCURY_TECHNOLOGY_MAPPER" "LUT"
	set_global_assignment -name "FLEX10K_TECHNOLOGY_MAPPER" "LUT"
	set_global_assignment -name "FLEX6K_TECHNOLOGY_MAPPER" "LUT"
	set_global_assignment -name "MAX7000_TECHNOLOGY_MAPPER" "PRODUCT TERM"
	set_global_assignment -name "STRATIX_TECHNOLOGY_MAPPER" "LUT"
	set_global_assignment -name "TURBO_BIT" "ON"
	set_global_assignment -name "WEAK_PULL_UP_RESISTOR" "OFF"
	set_global_assignment -name "ALLOW_XOR_GATE_USAGE" "ON"
	set_global_assignment -name "HARDCOPY_EXTERNAL_CLOCK_JITTER" "0.0 NS"
	set_global_assignment -name "CUT_OFF_CLEAR_AND_PRESET_PATHS" "ON"
	set_global_assignment -name "CUT_OFF_IO_PIN_FEEDBACK" "ON"
	set_global_assignment -name "CUT_OFF_PATHS_BETWEEN_CLOCK_DOMAINS" "ON"
	set_global_assignment -name "CUT_OFF_READ_DURING_WRITE_PATHS" "ON"
	set_global_assignment -name "DO_MIN_ANALYSIS" "ON"
	set_global_assignment -name "DO_MIN_TIMING" "OFF"
	set_global_assignment -name "INCLUDE_EXTERNAL_PIN_DELAYS_IN_FMAX_CALCULATIONS" "OFF"
	set_global_assignment -name "DEFAULT_HOLD_MULTICYCLE" "SAME AS MULTICYCLE"
	set_global_assignment -name "IGNORE_CLOCK_SETTINGS" "OFF"
	set_global_assignment -name "MAX_SCC_SIZE" "50"
	set_global_assignment -name "NUMBER_OF_DESTINATION_TO_REPORT" "10"
	set_global_assignment -name "NUMBER_OF_PATHS_TO_REPORT" "200"
	set_global_assignment -name "RUN_ALL_TIMING_ANALYSES" "ON"
	set_global_assignment -name "NUMBER_OF_SOURCES_PER_DESTINATION_TO_REPORT" "10"
	set_global_assignment -name "ENABLE_IP_DEBUG" "OFF"
	set_global_assignment -name "VERILOG_INPUT_VERSION" "VERILOG_2001"
	set_global_assignment -name "VHDL_INPUT_VERSION" "VHDL93"
	set_global_assignment -name "VHDL_SHOW_LMF_MAPPING_MESSAGES" "OFF"
	set_global_assignment -name "LAST_QUARTUS_VERSION" -section_id "dom" "3.0 SP2"
	set_global_assignment -name "ORIGINAL_QUARTUS_VERSION" -section_id "dom" "3.0"
	set_global_assignment -name "PROJECT_CREATION_TIME_DATE" -section_id "dom" "17:18:08  AUGUST 28, 2003"
	set_global_assignment -name "SHOW_REGISTRATION_MESSAGE" -section_id "dom" "ON"
	set_global_assignment -name "EDA_BOARD_DESIGN_TOOL" -section_id "dom" "<None>"
	set_global_assignment -name "EDA_DESIGN_ENTRY_SYNTHESIS_TOOL" -section_id "dom" "<None>"
	set_global_assignment -name "EDA_FORMAL_VERIFICATION_TOOL" -section_id "dom" "<None>"
	set_global_assignment -name "EDA_RESYNTHESIS_TOOL" -section_id "dom" "<None>"
	set_global_assignment -name "EDA_SIMULATION_TOOL" -section_id "dom" "ModelSim (VHDL output from Quartus II)"
	set_global_assignment -name "EDA_TIMING_ANALYSIS_TOOL" -section_id "dom" "<None>"
	set_global_assignment -name "EDA_INPUT_DATA_FORMAT" -section_id "eda_design_synthesis" "EDIF"
	set_global_assignment -name "EDA_INPUT_GND_NAME" -section_id "eda_design_synthesis" "GND"
	set_global_assignment -name "EDA_INPUT_VCC_NAME" -section_id "eda_design_synthesis" "VCC"
	set_global_assignment -name "EDA_RUN_TOOL_AUTOMATICALLY" -section_id "eda_design_synthesis" "OFF"
	set_global_assignment -name "EDA_OUTPUT_DATA_FORMAT" -section_id "eda_design_synthesis" "NONE"
	set_global_assignment -name "EDA_SHOW_LMF_MAPPING_MESSAGES" -section_id "eda_design_synthesis" "OFF"
	set_global_assignment -name "RESYNTHESIS_OPTIMIZATION_EFFORT" -section_id "eda_design_synthesis" "NORMAL"
	set_global_assignment -name "RESYNTHESIS_PHYSICAL_SYNTHESIS" -section_id "eda_design_synthesis" "NORMAL"
	set_global_assignment -name "RESYNTHESIS_RETIMING" -section_id "eda_design_synthesis" "FULL"
	set_global_assignment -name "USE_GENERATED_PHYSICAL_CONSTRAINTS" -section_id "eda_design_synthesis" "ON"
	set_global_assignment -name "EDA_EXCALIBUR_ATOMS_AS_SINGLE_STRIPE" -section_id "eda_simulation" "OFF"
	set_global_assignment -name "EDA_FLATTEN_BUSES" -section_id "eda_simulation" "OFF"
	set_global_assignment -name "EDA_GENERATE_FUNCTIONAL_NETLIST" -section_id "eda_simulation" "OFF"
	set_global_assignment -name "EDA_GENERATE_POWER_INPUT_FILE" -section_id "eda_simulation" "OFF"
	set_global_assignment -name "EDA_RUN_TOOL_AUTOMATICALLY" -section_id "eda_simulation" "OFF"
	set_global_assignment -name "EDA_MAINTAIN_DESIGN_HIERARCHY" -section_id "eda_simulation" "OFF"
	set_global_assignment -name "EDA_MAP_ILLEGAL_CHARACTERS" -section_id "eda_simulation" "ON"
	set_global_assignment -name "EDA_OUTPUT_DATA_FORMAT" -section_id "eda_simulation" "VHDL"
	set_global_assignment -name "EDA_TEST_BENCH_ENABLE_STATUS" -section_id "eda_simulation" "NOT_USED"
	set_global_assignment -name "EDA_TRUNCATE_LONG_HIERARCHY_PATHS" -section_id "eda_simulation" "OFF"
	set_global_assignment -name "EDA_INCLUDE_VHDL_CONFIGURATION_DECLARATION" -section_id "eda_simulation" "ON"
	set_global_assignment -name "EDA_WRITE_DEVICE_CONTROL_PORTS" -section_id "eda_simulation" "OFF"
	set_global_assignment -name "RESYNTHESIS_OPTIMIZATION_EFFORT" -section_id "eda_simulation" "NORMAL"
	set_global_assignment -name "RESYNTHESIS_PHYSICAL_SYNTHESIS" -section_id "eda_simulation" "NORMAL"
	set_global_assignment -name "RESYNTHESIS_RETIMING" -section_id "eda_simulation" "FULL"
	set_global_assignment -name "USE_GENERATED_PHYSICAL_CONSTRAINTS" -section_id "eda_simulation" "ON"
	set_global_assignment -name "EDA_EXCALIBUR_ATOMS_AS_SINGLE_STRIPE" -section_id "eda_timing_analysis" "OFF"
	set_global_assignment -name "EDA_FLATTEN_BUSES" -section_id "eda_timing_analysis" "OFF"
	set_global_assignment -name "EDA_GENERATE_FUNCTIONAL_NETLIST" -section_id "eda_timing_analysis" "OFF"
	set_global_assignment -name "EDA_LAUNCH_CMD_LINE_TOOL" -section_id "eda_timing_analysis" "OFF"
	set_global_assignment -name "EDA_RUN_TOOL_AUTOMATICALLY" -section_id "eda_timing_analysis" "OFF"
	set_global_assignment -name "EDA_MAINTAIN_DESIGN_HIERARCHY" -section_id "eda_timing_analysis" "OFF"
	set_global_assignment -name "EDA_MAP_ILLEGAL_CHARACTERS" -section_id "eda_timing_analysis" "OFF"
	set_global_assignment -name "EDA_OUTPUT_DATA_FORMAT" -section_id "eda_timing_analysis" "NONE"
	set_global_assignment -name "EDA_TRUNCATE_LONG_HIERARCHY_PATHS" -section_id "eda_timing_analysis" "OFF"
	set_global_assignment -name "EDA_INCLUDE_VHDL_CONFIGURATION_DECLARATION" -section_id "eda_timing_analysis" "OFF"
	set_global_assignment -name "EDA_WRITE_DEVICE_CONTROL_PORTS" -section_id "eda_timing_analysis" "OFF"
	set_global_assignment -name "RESYNTHESIS_OPTIMIZATION_EFFORT" -section_id "eda_timing_analysis" "NORMAL"
	set_global_assignment -name "RESYNTHESIS_PHYSICAL_SYNTHESIS" -section_id "eda_timing_analysis" "NORMAL"
	set_global_assignment -name "RESYNTHESIS_RETIMING" -section_id "eda_timing_analysis" "FULL"
	set_global_assignment -name "USE_GENERATED_PHYSICAL_CONSTRAINTS" -section_id "eda_timing_analysis" "ON"
	set_global_assignment -name "EDA_EXCALIBUR_ATOMS_AS_SINGLE_STRIPE" -section_id "eda_board_design" "OFF"
	set_global_assignment -name "EDA_FLATTEN_BUSES" -section_id "eda_board_design" "OFF"
	set_global_assignment -name "EDA_GENERATE_FUNCTIONAL_NETLIST" -section_id "eda_board_design" "OFF"
	set_global_assignment -name "EDA_RUN_TOOL_AUTOMATICALLY" -section_id "eda_board_design" "OFF"
	set_global_assignment -name "EDA_MAINTAIN_DESIGN_HIERARCHY" -section_id "eda_board_design" "OFF"
	set_global_assignment -name "EDA_MAP_ILLEGAL_CHARACTERS" -section_id "eda_board_design" "OFF"
	set_global_assignment -name "EDA_OUTPUT_DATA_FORMAT" -section_id "eda_board_design" "NONE"
	set_global_assignment -name "EDA_TRUNCATE_LONG_HIERARCHY_PATHS" -section_id "eda_board_design" "OFF"
	set_global_assignment -name "EDA_INCLUDE_VHDL_CONFIGURATION_DECLARATION" -section_id "eda_board_design" "OFF"
	set_global_assignment -name "EDA_WRITE_DEVICE_CONTROL_PORTS" -section_id "eda_board_design" "OFF"
	set_global_assignment -name "RESYNTHESIS_OPTIMIZATION_EFFORT" -section_id "eda_board_design" "NORMAL"
	set_global_assignment -name "RESYNTHESIS_PHYSICAL_SYNTHESIS" -section_id "eda_board_design" "NORMAL"
	set_global_assignment -name "RESYNTHESIS_RETIMING" -section_id "eda_board_design" "FULL"
	set_global_assignment -name "USE_GENERATED_PHYSICAL_CONSTRAINTS" -section_id "eda_board_design" "ON"
	set_global_assignment -name "EDA_EXCALIBUR_ATOMS_AS_SINGLE_STRIPE" -section_id "eda_formal_verification" "OFF"
	set_global_assignment -name "EDA_FLATTEN_BUSES" -section_id "eda_formal_verification" "OFF"
	set_global_assignment -name "EDA_GENERATE_FUNCTIONAL_NETLIST" -section_id "eda_formal_verification" "OFF"
	set_global_assignment -name "EDA_RUN_TOOL_AUTOMATICALLY" -section_id "eda_formal_verification" "OFF"
	set_global_assignment -name "EDA_MAINTAIN_DESIGN_HIERARCHY" -section_id "eda_formal_verification" "OFF"
	set_global_assignment -name "EDA_MAP_ILLEGAL_CHARACTERS" -section_id "eda_formal_verification" "OFF"
	set_global_assignment -name "EDA_OUTPUT_DATA_FORMAT" -section_id "eda_formal_verification" "NONE"
	set_global_assignment -name "EDA_TRUNCATE_LONG_HIERARCHY_PATHS" -section_id "eda_formal_verification" "OFF"
	set_global_assignment -name "EDA_INCLUDE_VHDL_CONFIGURATION_DECLARATION" -section_id "eda_formal_verification" "OFF"
	set_global_assignment -name "EDA_WRITE_DEVICE_CONTROL_PORTS" -section_id "eda_formal_verification" "OFF"
	set_global_assignment -name "RESYNTHESIS_OPTIMIZATION_EFFORT" -section_id "eda_formal_verification" "NORMAL"
	set_global_assignment -name "RESYNTHESIS_PHYSICAL_SYNTHESIS" -section_id "eda_formal_verification" "NORMAL"
	set_global_assignment -name "RESYNTHESIS_RETIMING" -section_id "eda_formal_verification" "FULL"
	set_global_assignment -name "USE_GENERATED_PHYSICAL_CONSTRAINTS" -section_id "eda_formal_verification" "ON"
	set_global_assignment -name "EDA_EXCALIBUR_ATOMS_AS_SINGLE_STRIPE" -section_id "eda_palace" "OFF"
	set_global_assignment -name "EDA_FLATTEN_BUSES" -section_id "eda_palace" "OFF"
	set_global_assignment -name "EDA_GENERATE_FUNCTIONAL_NETLIST" -section_id "eda_palace" "OFF"
	set_global_assignment -name "EDA_RUN_TOOL_AUTOMATICALLY" -section_id "eda_palace" "OFF"
	set_global_assignment -name "EDA_MAINTAIN_DESIGN_HIERARCHY" -section_id "eda_palace" "OFF"
	set_global_assignment -name "EDA_MAP_ILLEGAL_CHARACTERS" -section_id "eda_palace" "OFF"
	set_global_assignment -name "EDA_OUTPUT_DATA_FORMAT" -section_id "eda_palace" "NONE"
	set_global_assignment -name "EDA_TRUNCATE_LONG_HIERARCHY_PATHS" -section_id "eda_palace" "OFF"
	set_global_assignment -name "EDA_INCLUDE_VHDL_CONFIGURATION_DECLARATION" -section_id "eda_palace" "OFF"
	set_global_assignment -name "EDA_WRITE_DEVICE_CONTROL_PORTS" -section_id "eda_palace" "OFF"
	set_global_assignment -name "RESYNTHESIS_OPTIMIZATION_EFFORT" -section_id "eda_palace" "NORMAL"
	set_global_assignment -name "RESYNTHESIS_PHYSICAL_SYNTHESIS" -section_id "eda_palace" "NORMAL"
	set_global_assignment -name "RESYNTHESIS_RETIMING" -section_id "eda_palace" "FULL"
	set_global_assignment -name "USE_GENERATED_PHYSICAL_CONSTRAINTS" -section_id "eda_palace" "ON"
	set_global_assignment -name "DIVIDE_BASE_CLOCK_PERIOD_BY" -section_id "CLK_REF" "1"
	set_global_assignment -name "INCLUDE_EXTERNAL_PIN_DELAYS_IN_FMAX_CALCULATIONS" -section_id "CLK_REF" "ON"
	set_global_assignment -name "INVERT_BASE_CLOCK" -section_id "CLK_REF" "OFF"
	set_global_assignment -name "MULTIPLY_BASE_CLOCK_PERIOD_BY" -section_id "CLK_REF" "1"
	set_global_assignment -name "DUTY_CYCLE" -section_id "CLK_REF" "50"
	set_global_assignment -name "FMAX_REQUIREMENT" -section_id "CLK_REF" "20.0 MHz"
	set_global_assignment -name "BASED_ON_CLOCK_SETTINGS" -section_id "CLK1p" "CLK_REF"
	set_global_assignment -name "DIVIDE_BASE_CLOCK_PERIOD_BY" -section_id "CLK1p" "1"
	set_global_assignment -name "INVERT_BASE_CLOCK" -section_id "CLK1p" "OFF"
	set_global_assignment -name "MULTIPLY_BASE_CLOCK_PERIOD_BY" -section_id "CLK1p" "1"
	set_global_assignment -name "DUTY_CYCLE" -section_id "CLK1p" "50"
	set_global_assignment -name "BASED_ON_CLOCK_SETTINGS" -section_id "CLK2p" "CLK_REF"
	set_global_assignment -name "DIVIDE_BASE_CLOCK_PERIOD_BY" -section_id "CLK2p" "1"
	set_global_assignment -name "INVERT_BASE_CLOCK" -section_id "CLK2p" "OFF"
	set_global_assignment -name "MULTIPLY_BASE_CLOCK_PERIOD_BY" -section_id "CLK2p" "1"
	set_global_assignment -name "DUTY_CYCLE" -section_id "CLK2p" "50"
	set_global_assignment -name "BASED_ON_CLOCK_SETTINGS" -section_id "CLK3p" "CLK_REF"
	set_global_assignment -name "DIVIDE_BASE_CLOCK_PERIOD_BY" -section_id "CLK3p" "1"
	set_global_assignment -name "INVERT_BASE_CLOCK" -section_id "CLK3p" "OFF"
	set_global_assignment -name "MULTIPLY_BASE_CLOCK_PERIOD_BY" -section_id "CLK3p" "1"
	set_global_assignment -name "DUTY_CYCLE" -section_id "CLK3p" "50"
	set_global_assignment -name "BASED_ON_CLOCK_SETTINGS" -section_id "CLK4p" "CLK_REF"
	set_global_assignment -name "DIVIDE_BASE_CLOCK_PERIOD_BY" -section_id "CLK4p" "1"
	set_global_assignment -name "INVERT_BASE_CLOCK" -section_id "CLK4p" "OFF"
	set_global_assignment -name "MULTIPLY_BASE_CLOCK_PERIOD_BY" -section_id "CLK4p" "1"
	set_global_assignment -name "DUTY_CYCLE" -section_id "CLK4p" "50"

	# Compiler Assignments for dom
	set_project_settings -cmp "dom"
	set_global_assignment -name "ADV_NETLIST_OPT_FIT_LE_DUPLICATION" "OFF"
	set_global_assignment -name "ADV_NETLIST_OPT_FIT_LE_DUPLICATION_WITH_LUT_RESYNTH" "OFF"
	set_global_assignment -name "ADV_NETLIST_OPT_RETIME_CORE_AND_IO" "ON"
	set_global_assignment -name "ADV_NETLIST_OPT_SYNTH_GATE_RETIME" "OFF"
	set_global_assignment -name "ADV_NETLIST_OPT_SYNTH_USE_FITTER_INFO" "OFF"
	set_global_assignment -name "ADV_NETLIST_OPT_SYNTH_WYSIWYG_REMAP" "OFF"
	set_global_assignment -name "COMPILATION_LEVEL" "FULL"
	set_global_assignment -name "DISABLE_PLL_COMPENSATION_DELAY_CHANGE_WARNING" "OFF"
	set_global_assignment -name "DPRAM_32BIT_SINGLE_PORT_MODE_INPUT_EPXA1" "MEGALAB COLUMN 1"
	set_global_assignment -name "DPRAM_32BIT_SINGLE_PORT_MODE_OTHER_SIGNALS_EPXA1" "MEGALAB COLUMN 1"
	set_global_assignment -name "DPRAM_32BIT_SINGLE_PORT_MODE_OUTPUT_EPXA1" "LOWER TO 1ESB UPPER TO 1"
	set_global_assignment -name "DPRAM_8BIT_16BIT_SINGLE_PORT_MODE_INPUT_EPXA1" "MEGALAB COLUMN 1"
	set_global_assignment -name "DPRAM_8BIT_16BIT_SINGLE_PORT_MODE_OTHER_SIGNALS_EPXA1" "MEGALAB COLUMN 1"
	set_global_assignment -name "DPRAM_8BIT_16BIT_SINGLE_PORT_MODE_OUTPUT_EPXA1" "MEGALAB COLUMN 1"
	set_global_assignment -name "DPRAM_DEEP_MODE_INPUT_EPXA4_10" "MEGALAB COLUMN 3"
	set_global_assignment -name "DPRAM_DEEP_MODE_OTHER_SIGNALS_EPXA4_10" "MEGALAB COLUMN 3"
	set_global_assignment -name "DPRAM_DEEP_MODE_OUTPUT_EPXA4_10" "MEGALAB COLUMN 3"
	set_global_assignment -name "DPRAM_DUAL_PORT_MODE_INPUT_EPXA1" "DPRAM0 TO 1 DPRAM1 TO 2"
	set_global_assignment -name "DPRAM_DUAL_PORT_MODE_INPUT_EPXA4_10" "DPRAM0 TO 3 DPRAM1 TO 4"
	set_global_assignment -name "DPRAM_DUAL_PORT_MODE_OTHER_SIGNALS_EPXA1" "DPRAM0 TO 1 DPRAM1 TO 2"
	set_global_assignment -name "DPRAM_DUAL_PORT_MODE_OTHER_SIGNALS_EPXA4_10" "DPRAM0 TO 3 DPRAM1 TO 4"
	set_global_assignment -name "DPRAM_DUAL_PORT_MODE_OUTPUT_EPXA1" "DPRAM0 TO 1 DPRAM1 TO 2"
	set_global_assignment -name "DPRAM_DUAL_PORT_MODE_OUTPUT_EPXA4_10" "DPRAM0 TO 3 DPRAM1 TO 4ESB"
	set_global_assignment -name "DPRAM_INPUT_EPXA4_10" "DEFAULT INPUT ROUTING OPTIONS"
	set_global_assignment -name "DPRAM_OTHER_SIGNALS_EPXA4_10" "DEFAULT OTHER ROUTING OPTIONS"
	set_global_assignment -name "DPRAM_OUTPUT_EPXA4_10" "DEFAULT OUTPUT ROUTING OPTIONS"
	set_global_assignment -name "DPRAM_SINGLE_PORT_MODE_INPUT_EPXA4_10" "DPRAM0 TO 3 DPRAM1 TO 4"
	set_global_assignment -name "DPRAM_SINGLE_PORT_MODE_OTHER_SIGNALS_EPXA4_10" "DPRAM0 TO 3 DPRAM1 TO 4"
	set_global_assignment -name "DPRAM_SINGLE_PORT_MODE_OUTPUT_EPXA4_10" "DPRAM0 TO 3 DPRAM1 TO 4ESB"
	set_global_assignment -name "DPRAM_WIDE_MODE_INPUT_EPXA4_10" "LOWER TO 3 UPPER TO 4"
	set_global_assignment -name "DPRAM_WIDE_MODE_OTHER_SIGNALS_EPXA4_10" "MEGALAB COLUMN 3"
	set_global_assignment -name "DPRAM_WIDE_MODE_OUTPUT_EPXA4_10" "LOWER TO 3 UPPER TO 4ESB"
	set_global_assignment -name "DRC_FANOUT_EXCEEDING" "30"
	set_global_assignment -name "DRC_TOP_FANOUT" "50"
	set_global_assignment -name "DRC_REPORT_FANOUT_EXCEEDING" "OFF"
	set_global_assignment -name "DRC_REPORT_TOP_FANOUT" "OFF"
	set_global_assignment -name "ENABLE_DRC_SETTINGS" "OFF"
	set_global_assignment -name "RUN_DRC_DURING_COMPILATION" "OFF"
	set_global_assignment -name "FAMILY" "EXCALIBUR_ARM"
	set_global_assignment -name "FAST_FIT_COMPILATION" "OFF"
	set_global_assignment -name "FINAL_PLACEMENT_OPTIMIZATION" "AUTOMATICALLY"
	set_global_assignment -name "SEED" "1"
	set_global_assignment -name "IO_PLACEMENT_OPTIMIZATION" "ON"
	set_global_assignment -name "MERGE_HEX_FILE" "OFF"
	set_global_assignment -name "OPTIMIZE_HOLD_TIMING" "IO PATHS AND MINIMUM TPD PATHS"
	set_global_assignment -name "OPTIMIZE_IOC_REGISTER_PLACEMENT_FOR_TIMING" "ON"
	set_global_assignment -name "PHYSICAL_SYNTHESIS_COMBO_LOGIC" "OFF"
	set_global_assignment -name "PHYSICAL_SYNTHESIS_REGISTER_DUPLICATION" "OFF"
	set_global_assignment -name "PHYSICAL_SYNTHESIS_REGISTER_RETIMING" "OFF"
	set_global_assignment -name "PLD_TO_STRIPE_INTERRUPTS_EPXA4_10" "MEGALAB COLUMN 2"
	set_global_assignment -name "PROCESSOR_DEBUG_EXTENSIONS_EPXA4_10" "MEGALAB COLUMN 2"
	set_global_assignment -name "FOCUS_ENTITY_NAME" "|domapp"
	set_global_assignment -name "SAVE_DISK_SPACE" "ON"
	set_global_assignment -name "SIGNALPROBE_ALLOW_OVERUSE" "OFF"
	set_global_assignment -name "SIGNALPROBE_DURING_NORMAL_COMPILATION" "OFF"
	set_global_assignment -name "SMART_COMPILE_IGNORES_TDC_FOR_STRATIX_PLL_CHANGES" "OFF"
	set_global_assignment -name "SPEED_DISK_USAGE_TRADEOFF" "NORMAL"
	set_global_assignment -name "STRIPE_TO_PLD_BRIDGE_EPXA4_10" "MEGALAB COLUMN 1"
	set_global_assignment -name "STRIPE_TO_PLD_INTERRUPTS_EPXA4_10" "MEGALAB COLUMN 2"
	set_global_assignment -name "OPTIMIZE_TIMING" "NORMAL_COMPILATION"
	set_global_assignment -name "TRUE_WYSIWYG_FLOW" "OFF"
	set_global_assignment -name "LOGICLOCK_INCREMENTAL_COMPILE_ASSIGNMENT" "OFF"
	set_global_assignment -name "AUTO_INCREMENT_CONFIG_DEVICE_JTAG_USER_CODE" "ON"
	set_global_assignment -name "AUTO_RESTART_CONFIGURATION" "OFF"
	set_global_assignment -name "ENABLE_DEVICE_WIDE_OE" "OFF"
	set_global_assignment -name "ENABLE_DEVICE_WIDE_RESET" "OFF"
	set_global_assignment -name "CONFIGURATION_CLOCK_DIVISOR" "1"
	set_global_assignment -name "CONFIGURATION_CLOCK_FREQUENCY" "10 MHZ"
	set_global_assignment -name "CLOCK_SOURCE" "INTERNAL"
	set_global_assignment -name "COMPRESSION_MODE" "OFF"
	set_global_assignment -name "RESERVE_DATA0_AFTER_CONFIGURATION" "AS INPUT TRI-STATED"
	set_global_assignment -name "RESERVE_DATA7_THROUGH_DATA1_AFTER_CONFIGURATION" "USE AS REGULAR IO"
	set_global_assignment -name "DISABLE_NCS_AND_OE_PULLUPS_ON_CONFIG_DEVICE" "OFF"
	set_global_assignment -name "ENABLE_LOW_VOLTAGE_MODE_ON_CONFIG_DEVICE" "ON"
	set_global_assignment -name "FLEX10K_ENABLE_LOW_VOLTAGE_MODE_ON_CONFIG_DEVICE" "ON"
	set_global_assignment -name "FLEX6K_ENABLE_LOW_VOLTAGE_MODE_ON_CONFIG_DEVICE" "OFF"
	set_global_assignment -name "ENABLE_VREFA_PIN" "OFF"
	set_global_assignment -name "ENABLE_VREFB_PIN" "OFF"
	set_global_assignment -name "APEX20K_CONFIG_DEVICE_JTAG_USER_CODE" "FFFFFFFF"
	set_global_assignment -name "MERCURY_CONFIG_DEVICE_JTAG_USER_CODE" "FFFFFFFF"
	set_global_assignment -name "FLEX10K_CONFIG_DEVICE_JTAG_USER_CODE" "FFFFFFFF"
	set_global_assignment -name "STRATIX_CONFIG_DEVICE_JTAG_USER_CODE" "FFFFFFFF"
	set_global_assignment -name "EPROM_USE_CHECKSUM_AS_USERCODE" "OFF"
	set_global_assignment -name "GENERATE_CONFIG_HEXOUT_FILE" "OFF"
	set_global_assignment -name "GENERATE_CONFIG_ISC_FILE" "OFF"
	set_global_assignment -name "GENERATE_CONFIG_JAM_FILE" "OFF"
	set_global_assignment -name "GENERATE_CONFIG_JBC_FILE" "OFF"
	set_global_assignment -name "GENERATE_CONFIG_JBC_FILE_COMPRESSED" "ON"
	set_global_assignment -name "GENERATE_CONFIG_SVF_FILE" "OFF"
	set_global_assignment -name "GENERATE_HEX_FILE" "OFF"
	set_global_assignment -name "GENERATE_ISC_FILE" "OFF"
	set_global_assignment -name "GENERATE_JAM_FILE" "OFF"
	set_global_assignment -name "GENERATE_JBC_FILE" "OFF"
	set_global_assignment -name "GENERATE_JBC_FILE_COMPRESSED" "ON"
	set_global_assignment -name "GENERATE_RBF_FILE" "OFF"
	set_global_assignment -name "GENERATE_SVF_FILE" "OFF"
	set_global_assignment -name "GENERATE_TTF_FILE" "OFF"
	set_global_assignment -name "HEXOUT_FILE_COUNT_DIRECTION" "UP"
	set_global_assignment -name "HEXOUT_FILE_START_ADDRESS" "0"
	set_global_assignment -name "ENABLE_INIT_DONE_OUTPUT" "OFF"
	set_global_assignment -name "ENABLE_JTAG_BST_SUPPORT" "OFF"
	set_global_assignment -name "MAX7000_ENABLE_JTAG_BST_SUPPORT" "ON"
	set_global_assignment -name "RESERVE_NCEO_AFTER_CONFIGURATION" "USE AS REGULAR IO"
	set_global_assignment -name "RESERVE_NWS_NRS_NCS_CS_AFTER_CONFIGURATION" "USE AS REGULAR IO"
	set_global_assignment -name "ON_CHIP_BITSTREAM_DECOMPRESSION" "OFF"
	set_global_assignment -name "FLEX10K_ENABLE_LOCK_OUTPUT" "OFF"
	set_global_assignment -name "APEX20K_CONFIGURATION_SCHEME" "PASSIVE SERIAL"
	set_global_assignment -name "APEXII_CONFIGURATION_SCHEME" "PASSIVE SERIAL"
	set_global_assignment -name "MERCURY_CONFIGURATION_SCHEME" "PASSIVE SERIAL"
	set_global_assignment -name "EXCALIBUR_CONFIGURATION_SCHEME" "PASSIVE SERIAL"
	set_global_assignment -name "FLEX10K_CONFIGURATION_SCHEME" "PASSIVE SERIAL"
	set_global_assignment -name "FLEX6K_CONFIGURATION_SCHEME" "PASSIVE SERIAL"
	set_global_assignment -name "CYCLONE_CONFIGURATION_SCHEME" "PASSIVE SERIAL"
	set_global_assignment -name "STRATIX_CONFIGURATION_SCHEME" "PASSIVE SERIAL"
	set_global_assignment -name "RESERVE_RDYNBUSY_AFTER_CONFIGURATION" "USE AS REGULAR IO"
	set_global_assignment -name "RELEASE_CLEARS_BEFORE_TRI_STATES" "OFF"
	set_global_assignment -name "RESERVE_ALL_UNUSED_PINS" "AS OUTPUT DRIVING GROUND"
	set_global_assignment -name "RESERVE_PIN" "AS INPUT TRI-STATED"
	set_global_assignment -name "RESERVE_ASDO_AFTER_CONFIGURATION" "USE AS REGULAR IO"
	set_global_assignment -name "SECURITY_BIT" "OFF"
	set_global_assignment -name "USER_START_UP_CLOCK" "OFF"
	set_global_assignment -name "STRATIX_UPDATE_MODE" "STANDARD"
	set_global_assignment -name "APEX20K_JTAG_USER_CODE" "FFFFFFFF"
	set_global_assignment -name "MERCURY_JTAG_USER_CODE" "FFFFFFFF"
	set_global_assignment -name "FLEX10K_JTAG_USER_CODE" "7F"
	set_global_assignment -name "MAX7000_JTAG_USER_CODE" "FFFFFFFF"
	set_global_assignment -name "MAX7000S_JTAG_USER_CODE" "FFFF"
	set_global_assignment -name "STRATIX_JTAG_USER_CODE" "FFFFFFFF"
	set_global_assignment -name "USE_CHECKSUM_AS_USERCODE" "OFF"
	set_global_assignment -name "MAX7000_USE_CHECKSUM_AS_USERCODE" "OFF"
	set_global_assignment -name "APEX20K_CONFIGURATION_DEVICE" "EPC2"
	set_global_assignment -name "CYCLONE_CONFIGURATION_DEVICE" "EPC2"
	set_global_assignment -name "MERCURY_CONFIGURATION_DEVICE" "EPC2"
	set_global_assignment -name "EXCALIBUR_CONFIGURATION_DEVICE" "EPC2"
	set_global_assignment -name "FLEX10K_CONFIGURATION_DEVICE" "EPC2"
	set_global_assignment -name "FLEX6K_CONFIGURATION_DEVICE" "EPC1"
	set_global_assignment -name "STRATIX_CONFIGURATION_DEVICE" "EPC2"
	set_global_assignment -name "USE_CONFIGURATION_DEVICE" "ON"
	set_global_assignment -name "AUTO_INSERT_SLD_HUB_ENTITY" "ENABLE"
	set_global_assignment -name "HUB_ENTITY_NAME" "sld_hub"
	set_global_assignment -name "HUB_INSTANCE_NAME" "sld_hub_inst"
	set_global_assignment -name "AUTO_INCREMENT_CONFIG_DEVICE_JTAG_USER_CODE" "ON"
	set_global_assignment -name "AUTO_RESTART_CONFIGURATION" "OFF"
	set_global_assignment -name "BASE_PIN_OUT_FILE_ON_SAMEFRAME_DEVICE" "OFF"
	set_global_assignment -name "ENABLE_DEVICE_WIDE_OE" "OFF"
	set_global_assignment -name "ENABLE_DEVICE_WIDE_RESET" "OFF"
	set_global_assignment -name "CONFIGURATION_CLOCK_DIVISOR" "1"
	set_global_assignment -name "CONFIGURATION_CLOCK_FREQUENCY" "10 MHZ"
	set_global_assignment -name "CLOCK_SOURCE" "INTERNAL"
	set_global_assignment -name "COMPRESSION_MODE" "OFF"
	set_global_assignment -name "RESERVE_DATA0_AFTER_CONFIGURATION" "AS INPUT TRI-STATED"
	set_global_assignment -name "RESERVE_DATA7_THROUGH_DATA1_AFTER_CONFIGURATION" "USE AS REGULAR IO"
	set_global_assignment -name "DEVICE" "EPXA4F672I2"
	set_global_assignment -name "DISABLE_NCS_AND_OE_PULLUPS_ON_CONFIG_DEVICE" "OFF"
	set_global_assignment -name "ENABLE_LOW_VOLTAGE_MODE_ON_CONFIG_DEVICE" "ON"
	set_global_assignment -name "FLEX10K_ENABLE_LOW_VOLTAGE_MODE_ON_CONFIG_DEVICE" "ON"
	set_global_assignment -name "FLEX6K_ENABLE_LOW_VOLTAGE_MODE_ON_CONFIG_DEVICE" "OFF"
	set_global_assignment -name "ENABLE_VREFA_PIN" "OFF"
	set_global_assignment -name "ENABLE_VREFB_PIN" "OFF"
	set_global_assignment -name "APEX20K_CONFIG_DEVICE_JTAG_USER_CODE" "FFFFFFFF"
	set_global_assignment -name "MERCURY_CONFIG_DEVICE_JTAG_USER_CODE" "FFFFFFFF"
	set_global_assignment -name "FLEX10K_CONFIG_DEVICE_JTAG_USER_CODE" "FFFFFFFF"
	set_global_assignment -name "STRATIX_CONFIG_DEVICE_JTAG_USER_CODE" "FFFFFFFF"
	set_global_assignment -name "EPROM_USE_CHECKSUM_AS_USERCODE" "OFF"
	set_global_assignment -name "DEVICE_FILTER_PACKAGE" "FBGA"
	set_global_assignment -name "DEVICE_FILTER_PIN_COUNT" "672"
	set_global_assignment -name "DEVICE_FILTER_SPEED_GRADE" "2"
	set_global_assignment -name "GENERATE_CONFIG_HEXOUT_FILE" "OFF"
	set_global_assignment -name "GENERATE_CONFIG_ISC_FILE" "OFF"
	set_global_assignment -name "GENERATE_CONFIG_JAM_FILE" "OFF"
	set_global_assignment -name "GENERATE_CONFIG_JBC_FILE" "OFF"
	set_global_assignment -name "GENERATE_CONFIG_JBC_FILE_COMPRESSED" "ON"
	set_global_assignment -name "GENERATE_CONFIG_SVF_FILE" "OFF"
	set_global_assignment -name "GENERATE_HEX_FILE" "OFF"
	set_global_assignment -name "GENERATE_ISC_FILE" "OFF"
	set_global_assignment -name "GENERATE_JAM_FILE" "OFF"
	set_global_assignment -name "GENERATE_JBC_FILE" "OFF"
	set_global_assignment -name "GENERATE_JBC_FILE_COMPRESSED" "ON"
	set_global_assignment -name "GENERATE_RBF_FILE" "OFF"
	set_global_assignment -name "GENERATE_SVF_FILE" "OFF"
	set_global_assignment -name "GENERATE_TTF_FILE" "OFF"
	set_global_assignment -name "HEXOUT_FILE_COUNT_DIRECTION" "UP"
	set_global_assignment -name "HEXOUT_FILE_START_ADDRESS" "0"
	set_global_assignment -name "ENABLE_INIT_DONE_OUTPUT" "ON"
	set_global_assignment -name "ENABLE_JTAG_BST_SUPPORT" "OFF"
	set_global_assignment -name "MAX7000_ENABLE_JTAG_BST_SUPPORT" "ON"
	set_global_assignment -name "RESERVE_NCEO_AFTER_CONFIGURATION" "USE AS REGULAR IO"
	set_global_assignment -name "RESERVE_NWS_NRS_NCS_CS_AFTER_CONFIGURATION" "USE AS REGULAR IO"
	set_global_assignment -name "ON_CHIP_BITSTREAM_DECOMPRESSION" "OFF"
	set_global_assignment -name "FLEX10K_ENABLE_LOCK_OUTPUT" "OFF"
	set_global_assignment -name "APEX20K_CONFIGURATION_SCHEME" "PASSIVE SERIAL"
	set_global_assignment -name "APEXII_CONFIGURATION_SCHEME" "PASSIVE SERIAL"
	set_global_assignment -name "MERCURY_CONFIGURATION_SCHEME" "PASSIVE SERIAL"
	set_global_assignment -name "EXCALIBUR_CONFIGURATION_SCHEME" "PASSIVE SERIAL"
	set_global_assignment -name "FLEX10K_CONFIGURATION_SCHEME" "PASSIVE SERIAL"
	set_global_assignment -name "FLEX6K_CONFIGURATION_SCHEME" "PASSIVE SERIAL"
	set_global_assignment -name "CYCLONE_CONFIGURATION_SCHEME" "PASSIVE SERIAL"
	set_global_assignment -name "STRATIX_CONFIGURATION_SCHEME" "PASSIVE SERIAL"
	set_global_assignment -name "RESERVE_RDYNBUSY_AFTER_CONFIGURATION" "USE AS REGULAR IO"
	set_global_assignment -name "RELEASE_CLEARS_BEFORE_TRI_STATES" "OFF"
	set_global_assignment -name "RESERVE_ALL_UNUSED_PINS" "AS INPUT TRI-STATED"
	set_global_assignment -name "RESERVE_ASDO_AFTER_CONFIGURATION" "USE AS REGULAR IO"
	set_global_assignment -name "SECURITY_BIT" "OFF"
	set_global_assignment -name "USER_START_UP_CLOCK" "OFF"
	set_global_assignment -name "STRATIX_UPDATE_MODE" "STANDARD"
	set_global_assignment -name "APEX20K_JTAG_USER_CODE" "FFFFFFFF"
	set_global_assignment -name "MERCURY_JTAG_USER_CODE" "FFFFFFFF"
	set_global_assignment -name "FLEX10K_JTAG_USER_CODE" "7F"
	set_global_assignment -name "MAX7000_JTAG_USER_CODE" "FFFFFFFF"
	set_global_assignment -name "MAX7000S_JTAG_USER_CODE" "FFFF"
	set_global_assignment -name "STRATIX_JTAG_USER_CODE" "FFFFFFFF"
	set_global_assignment -name "USE_CHECKSUM_AS_USERCODE" "OFF"
	set_global_assignment -name "MAX7000_USE_CHECKSUM_AS_USERCODE" "OFF"
	set_global_assignment -name "APEX20K_CONFIGURATION_DEVICE" "EPC2"
	set_global_assignment -name "CYCLONE_CONFIGURATION_DEVICE" "EPC2"
	set_global_assignment -name "MERCURY_CONFIGURATION_DEVICE" "EPC2"
	set_global_assignment -name "EXCALIBUR_CONFIGURATION_DEVICE" "EPC2"
	set_global_assignment -name "FLEX10K_CONFIGURATION_DEVICE" "EPC2"
	set_global_assignment -name "FLEX6K_CONFIGURATION_DEVICE" "EPC1"
	set_global_assignment -name "STRATIX_CONFIGURATION_DEVICE" "EPC2"
	set_global_assignment -name "USE_CONFIGURATION_DEVICE" "ON"
	set_global_assignment -name "AUTO_ENABLE_SMART_COMPILE" "On"
	set_global_assignment -name "ENABLE_SIGNALTAP" "Off"

	# Simulator Assignments for dom
	set_project_settings -sim "dom"
	set_global_assignment -name "ADD_DEFAULT_PINS_TO_SIMULATION_OUTPUT_WAVEFORMS" "ON"
	set_global_assignment -name "CHECK_OUTPUTS" "OFF"
	set_global_assignment -name "SIMULATION_COVERAGE" "ON"
	set_global_assignment -name "ESTIMATE_POWER_CONSUMPTION" "OFF"
	set_global_assignment -name "GLITCH_DETECTION" "OFF"
	set_global_assignment -name "GLITCH_INTERVAL" "1NS"
	set_global_assignment -name "POWER_ESTIMATION_START_TIME" "0 NS"
	set_global_assignment -name "SETUP_HOLD_DETECTION" "OFF"
	set_global_assignment -name "SIMULATION_MODE" "TIMING"
	set_global_assignment -name "START_TIME" "0NS"

	# Software Build Assignments for release
	set_project_settings -swb "release"
	set_global_assignment -name "BYTE_ORDER" "LITTLE ENDIAN"
	set_global_assignment -name "DO_POST_BUILD_COMMAND_LINE" "OFF"
	set_global_assignment -name "OUTPUT_TYPE" "INTEL HEX"
	set_global_assignment -name "PROCESSOR" "ARM922T"
	set_global_assignment -name "PROGRAMMING_FILE_TYPE" "NO PROGRAMMING FILE"
	set_global_assignment -name "TOOLSET" "CUSTOM BUILD"
	set_global_assignment -name "USE_C_PREPROCESSOR_FOR_GNU_ASM_FILES" "ON"

	# Software Build Assignments for debug
	set_project_settings -swb "debug"
	set_global_assignment -name "BYTE_ORDER" "LITTLE ENDIAN"
	set_global_assignment -name "DO_POST_BUILD_COMMAND_LINE" "OFF"
	set_global_assignment -name "OUTPUT_TYPE" "INTEL HEX"
	set_global_assignment -name "PROCESSOR" "ARM922T"
	set_global_assignment -name "PROGRAMMING_FILE_TYPE" "NO PROGRAMMING FILE"
	set_global_assignment -name "TOOLSET" "CUSTOM BUILD"
	set_global_assignment -name "USE_C_PREPROCESSOR_FOR_GNU_ASM_FILES" "ON"

	# Entity Assignments for alt_exc_stripe
	set_instance_assignment -name "ADV_NETLIST_OPT_ALLOWED" -to "lcell_hgrant" -entity "alt_exc_stripe" "NEVER_ALLOW"
	set_instance_assignment -name "ADV_NETLIST_OPT_ALLOWED" -to "lcell_hresp0" -entity "alt_exc_stripe" "NEVER_ALLOW"
	set_instance_assignment -name "ADV_NETLIST_OPT_ALLOWED" -to "lcell_hresp1" -entity "alt_exc_stripe" "NEVER_ALLOW"
	set_instance_assignment -name "IMPLEMENT_AS_OUTPUT_OF_LOGIC_CELL" -to "lcell_hgrant" -entity "alt_exc_stripe" "ON"
	set_instance_assignment -name "IMPLEMENT_AS_OUTPUT_OF_LOGIC_CELL" -to "lcell_hresp0" -entity "alt_exc_stripe" "ON"
	set_instance_assignment -name "IMPLEMENT_AS_OUTPUT_OF_LOGIC_CELL" -to "lcell_hresp1" -entity "alt_exc_stripe" "ON"

	# Commit assignments
	export_assignments

	# Close project
	if {$need_to_close_project} {
		project_close
	}
}
