BEGIN {
    types["config"] = 0;
    types["iceboot"] = 1;
    types["test"] = 2;
    types["domapp"] = 3;
    ntypes = 0;
    for (ii in types) ntypes++;
    
    comps["comm"] = 0;
    comps["acquisition"] = 1;
    comps["flasher"] = 2;
    comps["pulser"] = 3;
    comps["local"] = 4;

    ncomps = 0;
    for (ii in comps) ncomps++;
}


/[a-zA-Z]+[ \t]+[a-zA-Z]+[ \t]+[0-9]+$/ {
    versions[types[$1], comps[$2]] = $3;
}

END {
    print "/* autogenerated by mkhdr.awk! */";
    print "const static int fpga_versions[" ntypes "][" ncomps "] = {";
    
    for (i=0; i<ntypes; i++) { 
	printf "   { ";
	for (j=0; j<ncomps; j++) {
	    printf "%d", versions[i, j];
	    if (j!=ncomps-1) printf ", ";
	}
	print "},";
    }
    print "};";
}
