
END {
    print "/* autogenerated by mkhdr.awk! */";
    print "const static int fpga_versions[" ntypes "][" ncomps "] = {";
    
    for (i=0; i<ntypes; i++) { 
	printf "   { ";
	for (j=0; j<ncomps; j++) {
	    printf "%d", versions[i, j];
	    if (j!=ncomps-1) printf ", ";
	}
	print "},";
    }
    print "};";
}
