#!/bin/bash

#
# script files location...
#
sdir=../../scripts

# layout of file (everything is a 16bit word):
#   fpga_type (from current dir fpga_type file...)
#   build_num0 (from current dir build_num file...)
#   build_num1 (from current dir build_num file...)
#   versions (read from sdata.txt):
#

echo "/* autogenerated .h file from mkhdr.sh */"
echo " "
vals=`cut -d ' ' -f 1 ${sdir}/sdata.txt`
for f in $vals; do
    nm=`grep ^${f} ${sdir}/sdata.txt | cut -d ' ' -f 2 \
	| tr [:lower:] [:upper:]`
    printf "#define FPGA_VERSIONS_%s %d\n" $nm $f
done








