END {
    print "-- autogenerated by mkmif.awk!";
    print "WIDTH=16;";
    print "DEPTH=128;";
    print " ";
    print "ADDRESS_RADIX=UNS;";
    print "DATA_RADIX=UNS;";
    print " ";
    print "CONTENT BEGIN";
    print "        0 : 14889";
    print "        1 : " and(rshift(build, 16), 65535);
    print "        2 : " and(build, 65535);

    idx = types[type];
    for (i=0; i<ncomps; i++) {
	print "        " (3+i) " : " versions[idx, i];
    }

    print "        [" (3 + ncomps) "..128] : 0";
    print "END;";
}


